SELECT DISTINCT ?legislature ?legislatureLabel ?adminArea ?adminAreaLabel ?adminAreaTypes ?legislaturePost ?legislaturePostLabel ?numberOfSeats WHERE {
  {
    SELECT DISTINCT ?adminArea
                (MIN(?primarySort) AS ?primarySort)
                (GROUP_CONCAT(DISTINCT REPLACE(STR(?adminAreaType), '^.*/', ''); SEPARATOR=" ") AS ?adminAreaTypes) {
  {
    VALUES (?adminArea ?primarySort ?adminAreaType) { (wd:Q155 1 wd:Q6256) }
  } UNION {
    # Find regional admin areas of this country (generally FLACSen)
    ?adminArea wdt:P17 wd:Q155 ;
          wdt:P31/wdt:P279* wd:Q10864048
    VALUES (?primarySort ?adminAreaType) { (2 wd:Q10864048) }
  } UNION {
    # Find cities or municipalities with populations of over 250k
    VALUES ?adminAreaType { wd:Q515 wd:Q15284 }
    ?adminArea wdt:P17 wd:Q155 ;
       wdt:P31/wdt:P279* ?adminAreaType ;
       wdt:P1082 ?population .
    FILTER (?population > 250000)
    VALUES ?primarySort { 3 }
  } UNION {
    VALUES (?adminArea ?primarySort ?adminAreaType) {
      (wd:Q986015 4 wd:Q24238356)
      (wd:Q2223621 4 wd:Q24238356)
      (wd:Q4261706 4 wd:Q24238356)
      (wd:Q4262088 4 wd:Q24238356)
      (wd:Q4262095 4 wd:Q24238356)
      (wd:Q4262100 4 wd:Q24238356)
      (wd:Q4262104 4 wd:Q24238356)
      (wd:Q4262119 4 wd:Q24238356)
      (wd:Q4262126 4 wd:Q24238356)
      (wd:Q4262135 4 wd:Q24238356)
      (wd:Q4274227 4 wd:Q24238356)
      (wd:Q4274232 4 wd:Q24238356)
      (wd:Q4274237 4 wd:Q24238356)
      (wd:Q4305949 4 wd:Q24238356)
      (wd:Q4305958 4 wd:Q24238356)
      (wd:Q4306002 4 wd:Q24238356)
      (wd:Q4352002 4 wd:Q24238356)
      (wd:Q4352005 4 wd:Q24238356)
      (wd:Q4409038 4 wd:Q24238356)
      (wd:Q4409861 4 wd:Q24238356)
      (wd:Q4409869 4 wd:Q24238356)
      (wd:Q4445052 4 wd:Q24238356)
      (wd:Q4445053 4 wd:Q24238356)
      (wd:Q4445054 4 wd:Q24238356)
      (wd:Q4445056 4 wd:Q24238356)
      (wd:Q4502358 4 wd:Q24238356)
      (wd:Q4502363 4 wd:Q24238356)
      (wd:Q4555498 4 wd:Q24238356)
      (wd:Q4675493 4 wd:Q24238356)
      (wd:Q4675774 4 wd:Q24238356)
      (wd:Q6372512 4 wd:Q24238356)
      (wd:Q28680501 4 wd:Q24238356)
      (wd:Q817227 4 wd:Q24238356)
      (wd:Q318314 4 wd:Q24238356)
      (wd:Q504755 4 wd:Q24238356)
      (wd:Q732905 4 wd:Q24238356)
      (wd:Q56654088 4 wd:Q24238356)
      (wd:Q56654090 4 wd:Q24238356)
      (wd:Q56654092 4 wd:Q24238356)
      (wd:Q56654095 4 wd:Q24238356)
      (wd:Q56654097 4 wd:Q24238356)
      (wd:Q56654099 4 wd:Q24238356)
      (wd:Q56654101 4 wd:Q24238356)
      (wd:Q56654103 4 wd:Q24238356)
      (wd:Q56654105 4 wd:Q24238356)
      (wd:Q56654107 4 wd:Q24238356)
      (wd:Q56654109 4 wd:Q24238356)
      (wd:Q56654111 4 wd:Q24238356)
      (wd:Q56654113 4 wd:Q24238356)
      (wd:Q56654115 4 wd:Q24238356)
      (wd:Q56654117 4 wd:Q24238356)
      (wd:Q56654119 4 wd:Q24238356)
      (wd:Q56654121 4 wd:Q24238356)
    }
  }

  # Remove admin areas that have ended
  FILTER NOT EXISTS { ?adminArea wdt:P582|wdt:P576 ?adminAreaEnd . FILTER (?adminAreaEnd < NOW()) }
} GROUP BY ?adminArea ORDER BY ?primarySort ?adminArea

  }

  ?adminArea wdt:P194/wdt:P527? ?legislature .

  VALUES ?legislatureType { wd:Q11204 wd:Q10553309 }
  ?legislature wdt:P31/wdt:P279* ?legislatureType .

  # Exclude legislatures (but never legislative houses) that "has part"
  # legislative houses or other legislatures. This happens with UK councils
  # (see e.g. Q17021809).
  FILTER (?legislatureType != wd:Q11204 || NOT EXISTS {
    VALUES ?subLegislatureType { wd:Q10553309 wd:Q11204 }
    ?legislature wdt:P527 ?legislaturePart .
    ?legislaturePart  wdt:P31/wdt:P279* ?subLegislatureType .
  })

  # Attempt to find the position for members of the legislature
  OPTIONAL {
    # Both "has part" and "has parts of class" seem to be used; with the latter not in keeping with the draft model
    ?legislature wdt:P527|wdt:P2670 ?legislaturePost .
    ?legislaturePost wdt:P31/wdt:P279* wd:Q4164871 .
    # Make sure positions are either legislators or councillors (and so exclude e.g. mayors)
    FILTER EXISTS {
      VALUES ?legislaturePostSuperType { wd:Q4175034 wd:Q708492 }
      ?legislaturePost wdt:P279+ ?legislaturePostSuperType .
    }
    # Some legislatures, e.g. Q633872 have multiple 'has part's pointing at
    # posts, where one subclasses the other. In this case, we want to only
    # return the parent, and then consider superclasses in the legislative
    # membership query, so that we don't end up with duplicate legislature
    # entries in the legislative index.
    FILTER NOT EXISTS {
      ?legislature wdt:P527|wdt:P2670 ?legislaturePostOther .
      ?legislaturePost wdt:P279+ ?legislaturePostOther .
    }
    FILTER NOT EXISTS { ?legislaturePost wdt:P576 ?legislaturePostEnd . FILTER (?legislaturePostEnd < NOW()) }
  }
  OPTIONAL {
    ?legislature wdt:P1342 ?numberOfSeats .
  }

  # Remove legislatures that have ended
  FILTER NOT EXISTS { ?legislature wdt:P576 ?legislatureEnd . FILTER (?legislatureEnd < NOW()) }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,pt-br,pt". }
} ORDER BY ?primarySort ?legislature ?legislaturePost
