SELECT DISTINCT ?executive ?executiveLabel ?adminArea ?adminAreaLabel ?adminAreaTypes ?position ?positionLabel {
  {
    SELECT DISTINCT ?adminArea
                (MIN(?primarySort) AS ?primarySort)
                (GROUP_CONCAT(DISTINCT REPLACE(STR(?adminAreaType), '^.*/', ''); SEPARATOR=" ") AS ?adminAreaTypes) {
  {
    VALUES (?adminArea ?primarySort ?adminAreaType) { (wd:Q155 1 wd:Q6256) }
  } UNION {
    # Find regional admin areas of this country (generally FLACSen)
    ?adminArea wdt:P17 wd:Q155 ;
          wdt:P31/wdt:P279* wd:Q10864048
    VALUES (?primarySort ?adminAreaType) { (2 wd:Q10864048) }
  } UNION {
    # Find cities or municipalities with populations of over 250k
    VALUES ?adminAreaType { wd:Q515 wd:Q15284 }
    ?adminArea wdt:P17 wd:Q155 ;
       wdt:P31/wdt:P279* ?adminAreaType ;
       wdt:P1082 ?population .
    FILTER (?population > 250000)
    VALUES ?primarySort { 3 }
  } UNION {
    VALUES (?adminArea ?primarySort ?adminAreaType) {
      (wd:Q986015 4 wd:Q24238356)
      (wd:Q2223621 4 wd:Q24238356)
      (wd:Q4261706 4 wd:Q24238356)
      (wd:Q4262088 4 wd:Q24238356)
      (wd:Q4262095 4 wd:Q24238356)
      (wd:Q4262100 4 wd:Q24238356)
      (wd:Q4262104 4 wd:Q24238356)
      (wd:Q4262119 4 wd:Q24238356)
      (wd:Q4262126 4 wd:Q24238356)
      (wd:Q4262135 4 wd:Q24238356)
      (wd:Q4274227 4 wd:Q24238356)
      (wd:Q4274232 4 wd:Q24238356)
      (wd:Q4274237 4 wd:Q24238356)
      (wd:Q4305949 4 wd:Q24238356)
      (wd:Q4305958 4 wd:Q24238356)
      (wd:Q4306002 4 wd:Q24238356)
      (wd:Q4352002 4 wd:Q24238356)
      (wd:Q4352005 4 wd:Q24238356)
      (wd:Q4409038 4 wd:Q24238356)
      (wd:Q4409861 4 wd:Q24238356)
      (wd:Q4409869 4 wd:Q24238356)
      (wd:Q4445052 4 wd:Q24238356)
      (wd:Q4445053 4 wd:Q24238356)
      (wd:Q4445054 4 wd:Q24238356)
      (wd:Q4445056 4 wd:Q24238356)
      (wd:Q4502358 4 wd:Q24238356)
      (wd:Q4502363 4 wd:Q24238356)
      (wd:Q4555498 4 wd:Q24238356)
      (wd:Q4675493 4 wd:Q24238356)
      (wd:Q4675774 4 wd:Q24238356)
      (wd:Q6372512 4 wd:Q24238356)
      (wd:Q28680501 4 wd:Q24238356)
      (wd:Q817227 4 wd:Q24238356)
      (wd:Q318314 4 wd:Q24238356)
      (wd:Q504755 4 wd:Q24238356)
      (wd:Q732905 4 wd:Q24238356)
      (wd:Q56654088 4 wd:Q24238356)
      (wd:Q56654090 4 wd:Q24238356)
      (wd:Q56654092 4 wd:Q24238356)
      (wd:Q56654095 4 wd:Q24238356)
      (wd:Q56654097 4 wd:Q24238356)
      (wd:Q56654099 4 wd:Q24238356)
      (wd:Q56654101 4 wd:Q24238356)
      (wd:Q56654103 4 wd:Q24238356)
      (wd:Q56654105 4 wd:Q24238356)
      (wd:Q56654107 4 wd:Q24238356)
      (wd:Q56654109 4 wd:Q24238356)
      (wd:Q56654111 4 wd:Q24238356)
      (wd:Q56654113 4 wd:Q24238356)
      (wd:Q56654115 4 wd:Q24238356)
      (wd:Q56654117 4 wd:Q24238356)
      (wd:Q56654119 4 wd:Q24238356)
      (wd:Q56654121 4 wd:Q24238356)
    }
  }

  # Remove admin areas that have ended
  FILTER NOT EXISTS { ?adminArea wdt:P582|wdt:P576 ?adminAreaEnd . FILTER (?adminAreaEnd < NOW()) }
} GROUP BY ?adminArea ORDER BY ?primarySort ?adminArea

  }

  OPTIONAL {
    {
      ?position p:P1001 [ wikibase:rank ?appliesToJurisdictionRank ; ps:P1001 ?adminArea ] ;
        wdt:P31/wdt:P279* wd:Q4164871 .
      FILTER (?appliesToJurisdictionRank != wikibase:DeprecatedRank)
      FILTER EXISTS {
        VALUES ?positionSuperclass { wd:Q2285706 wd:Q30461 }
        ?position wdt:P279* ?positionSuperclass .
      }
    } UNION {
      ?adminArea wdt:P1313 ?position
    }

    OPTIONAL {
      ?position wdt:P361 ?executive .
      # Exclude executives that are privy councils
      FILTER NOT EXISTS { ?executive wdt:P31/wdt:P279* wd:Q6528244 }
      # Exclude executives which aren't direct parents of the position
      FILTER NOT EXISTS { ?position wdt:P361 ?other . ?other wdt:P361+ ?executive }
      # Filter positions that have been dissolved
      FILTER NOT EXISTS { ?position wdt:P576 ?positionEnd . FILTER (?positionEnd < NOW()) }
    }
  }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,pt-br,pt". }
} ORDER BY ?primarySort ?executive ?position
